"""labels

Revision ID: 14edc679fb65
Revises: 16a546d4aa6a
Create Date: 2015-07-19 09:09:52.574940

"""

# revision identifiers, used by Alembic.
revision = '14edc679fb65'
down_revision = '16a546d4aa6a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('board_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_slug'), 'labels', ['slug'], unique=False)
    op.add_column(u'cards', sa.Column('labels', postgresql.ARRAY(sa.Text(), dimensions=1), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'cards', 'labels')
    op.drop_index(op.f('ix_labels_slug'), table_name='labels')
    op.drop_table('labels')
    ### end Alembic commands ###
