"""real ids for users, do not lowercase includes

Revision ID: 16a546d4aa6a
Revises: 2a17b33cb276
Create Date: 2015-05-18 10:09:39.619695

"""

# revision identifiers, used by Alembic.
revision = '16a546d4aa6a'
down_revision = '2a17b33cb276'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_id', sa.String(length=50), nullable=True))
    ### end Alembic commands ###

    op.execute('''
CREATE OR REPLACE FUNCTION markdown_link(source text) RETURNS json as $$
DECLARE link json;
BEGIN

SELECT row_to_json(p) INTO link FROM (
  SELECT
    CASE WHEN position('(' in source) = 0 OR position(']' in source) = 0 THEN source
         ELSE split_part(split_part(source, '[', 2), ']', 1)
    END AS text,
    CASE WHEN position('(' in source) = 0 OR position(']' in source) = 0 THEN source
         ELSE split_part(split_part(source, '(', 2), ')', 1)
    END AS url
)p;

RETURN link;
END;
$$  LANGUAGE plpgsql;
    ''')

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_id')
    ### end Alembic commands ###

    op.execute('''
CREATE OR REPLACE FUNCTION markdown_link(source text) RETURNS json as $$
DECLARE link json;
BEGIN

SELECT row_to_json(p) INTO link FROM (
  SELECT
    CASE WHEN position('(' in source) = 0 OR position(']' in source) = 0 THEN source
         ELSE split_part(split_part(source, '[', 2), ']', 1)
    END AS text,
    CASE WHEN position('(' in source) = 0 OR position(']' in source) = 0 THEN source
         ELSE lower(split_part(split_part(source, '(', 2), ')', 1))
    END AS url
)p;

RETURN link;
END;
$$  LANGUAGE plpgsql;
    ''')
