"""initial

Revision ID: 181a9a17af6e
Revises: None
Create Date: 2015-03-25 22:39:01.357236

"""

# revision identifiers, used by Alembic.
revision = '181a9a17af6e'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('custom_domain_enabled', sa.Boolean(), nullable=True),
    sa.Column('custom_domain_paypal_agreement_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('fullName', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('gravatarHash', sa.String(length=32), nullable=True),
    sa.Column('avatarHash', sa.String(length=32), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boards',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('webhook', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('subdomain', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_subdomain'), 'boards', ['subdomain'], unique=True)
    op.create_table('lists',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('board_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('pos', sa.Integer(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lists_slug'), 'lists', ['slug'], unique=False)
    op.create_index(op.f('ix_lists_visible'), 'lists', ['visible'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('list_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('pos', sa.Integer(), nullable=True),
    sa.Column('due', sa.DateTime(), nullable=True),
    sa.Column('checklists', postgresql.JSONB(), nullable=True),
    sa.Column('attachments', postgresql.JSONB(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_slug'), 'cards', ['slug'], unique=False)
    op.create_index(op.f('ix_cards_visible'), 'cards', ['visible'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('card_id', sa.String(length=50), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_index(op.f('ix_cards_visible'), table_name='cards')
    op.drop_index(op.f('ix_cards_slug'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_lists_visible'), table_name='lists')
    op.drop_index(op.f('ix_lists_slug'), table_name='lists')
    op.drop_table('lists')
    op.drop_index(op.f('ix_boards_subdomain'), table_name='boards')
    op.drop_table('boards')
    op.drop_table('users')
    ### end Alembic commands ###
