"""calc page title based on markdown heading

Revision ID: 1caa6b800107
Revises: 3b551cd3d9e
Create Date: 2015-04-13 13:24:39.286674

"""

# revision identifiers, used by Alembic.
revision = '1caa6b800107'
down_revision = '3b551cd3d9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('pageTitle', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'pageTitle')
    ### end Alembic commands ###
