"""nullable=False everywhere

Revision ID: 1e3b6fd449
Revises: 175c090fade
Create Date: 2015-07-22 22:54:57.871988

"""

# revision identifiers, used by Alembic.
revision = '1e3b6fd449'
down_revision = '175c090fade'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'subdomain',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('boards', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cards', 'list_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cards', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('cards', 'shortLink',
               existing_type=sa.VARCHAR(length=35),
               nullable=False)
    op.alter_column('cards', 'slug',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('labels', 'board_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('lists', 'board_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('lists', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('lists', 'slug',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lists', 'slug',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('lists', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('lists', 'board_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('labels', 'board_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cards', 'slug',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('cards', 'shortLink',
               existing_type=sa.VARCHAR(length=35),
               nullable=True)
    op.alter_column('cards', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('cards', 'list_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('boards', 'user_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('boards', 'subdomain',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###
