"""comments preferences

Revision ID: 280dbf4fee6e
Revises: efa8e43ae42
Create Date: 2015-09-25 21:33:19.791867

"""

# revision identifiers, used by Alembic.
revision = '280dbf4fee6e'
down_revision = 'efa8e43ae42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
CREATE OR REPLACE FUNCTION preferences(text) RETURNS json as $$
DECLARE prefs json;
BEGIN

WITH pcards AS (
  SELECT * FROM prefs_cards WHERE domain = $1 OR subdomain = $1
), includes AS (
  SELECT attachment->>'url' AS url
  FROM
    (SELECT jsonb_array_elements(pcards.attachments->'attachments') AS attachment
     FROM pcards
     WHERE name = 'includes')t
  UNION SELECT markdown_link(checkitem->>'name')->>'url' AS url
  FROM
    (SELECT jsonb_array_elements(c->'checkItems') AS checkitem
       FROM
         (SELECT jsonb_array_elements(checklists->'checklists') AS c
          FROM pcards
          WHERE name = 'includes')f
    )p
    WHERE checkitem->>'state' = 'complete'
), nav AS (
  SELECT markdown_link(checkitem->>'name') AS url
  FROM
    (SELECT jsonb_array_elements(c->'checkItems') AS checkitem
     FROM
       (SELECT jsonb_array_elements(jsonb_extract_path(checklists, 'checklists')) AS c
        FROM pcards
        WHERE name = 'nav')f
    )p
), comments AS (
  SELECT
    json_object_agg(checkitem->>'name', checkitem->>'state' = 'complete') AS opts
  FROM
    (SELECT jsonb_array_elements(c->'checkItems') AS checkitem
     FROM
      (SELECT jsonb_array_elements(jsonb_extract_path(checklists, 'checklists')) AS c
       FROM pcards
       WHERE name = 'comments')f
    )p
)

SELECT json_object_agg(key, value) INTO prefs
FROM (
  SELECT key, value::json FROM
      (
         (SELECT 'includes' AS key,
                 to_json(array_agg(url))::text AS value
          FROM includes)
      UNION
         (SELECT 'nav' AS key,
                 to_json(array_agg(url))::text AS value
          FROM nav)
      UNION 
        (SELECT 'comments' AS key,
                opts::text AS value
        FROM comments)
      UNION 
         (SELECT 'header' AS key,
                 row_to_json(h)::text AS value
          FROM (SELECT "desc" AS text, cover AS image FROM pcards WHERE name = 'header')h)
      UNION 
         (SELECT pcards.name AS key,
                 to_json(pcards.desc::text)::text AS value
          FROM pcards
          WHERE pcards.name IN ('posts-per-page', 'favicon', 'excerpts', 'aside', 'domain'))
      )kv
)kvj
;

RETURN prefs;

END;
$$  LANGUAGE plpgsql;
    ''')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
CREATE OR REPLACE FUNCTION preferences(text) RETURNS json as $$
DECLARE prefs json;
BEGIN

WITH pcards AS (
  SELECT * FROM prefs_cards WHERE domain = $1 OR subdomain = $1
), includes AS (
  SELECT attachment->>'url' AS url
  FROM
    (SELECT jsonb_array_elements(pcards.attachments->'attachments') AS attachment
     FROM pcards
     WHERE name = 'includes')t
  UNION SELECT markdown_link(checkitem->>'name')->>'url' AS url
  FROM
    (SELECT jsonb_array_elements(c->'checkItems') AS checkitem
       FROM
         (SELECT jsonb_array_elements(checklists->'checklists') AS c
          FROM pcards
          WHERE name = 'includes')f
    )p
    WHERE checkitem->>'state' = 'complete'
), nav AS (
  SELECT markdown_link(checkitem->>'name') AS url
  FROM
    (SELECT jsonb_array_elements(c->'checkItems') AS checkitem
     FROM
       (SELECT jsonb_array_elements(jsonb_extract_path(checklists, 'checklists')) AS c
        FROM pcards
        WHERE name = 'nav')f
    )p
)

SELECT json_object_agg(key, value) INTO prefs
FROM (
  SELECT key, value::json FROM
      (
         (SELECT 'includes' AS key,
                 to_json(array_agg(url))::text AS value
          FROM includes)
      UNION
         (SELECT 'nav' AS key,
                 to_json(array_agg(url))::text AS value
          FROM nav)
      UNION 
         (SELECT 'header' AS key,
                 row_to_json(h)::text AS value
          FROM (SELECT "desc" AS text, cover AS image FROM pcards WHERE name = 'header')h)
      UNION 
         (SELECT pcards.name AS key,
                 to_json(pcards.desc::text)::text AS value
          FROM pcards
          WHERE pcards.name IN ('posts-per-page', 'favicon', 'excerpts', 'aside', 'domain'))
      )kv
)kvj
;

RETURN prefs;

END;
$$  LANGUAGE plpgsql;
    ''')
    ### end Alembic commands ###
