"""comment body.

Revision ID: 295ce675e7bf
Revises: 105dc3e59977
Create Date: 2015-08-25 23:46:02.453692

"""

# revision identifiers, used by Alembic.
revision = '295ce675e7bf'
down_revision = '105dc3e59977'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'body')
    ### end Alembic commands ###
