"""remove crated_on column, add shortLink

Revision ID: 2a17b33cb276
Revises: 7c660464f9f
Create Date: 2015-04-19 14:22:49.129538

"""

# revision identifiers, used by Alembic.
revision = '2a17b33cb276'
down_revision = '7c660464f9f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('shortLink', sa.String(length=35), nullable=True))
    op.create_unique_constraint(None, 'boards', ['shortLink'])
    op.add_column('cards', sa.Column('shortLink', sa.String(length=35), nullable=True))
    op.create_unique_constraint(None, 'cards', ['shortLink'])
    op.drop_column('cards', 'created_on')
    op.drop_column('comments', 'created_on')
    op.drop_column('lists', 'created_on')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('cards', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cards', type_='unique')
    op.drop_column('cards', 'shortLink')
    op.drop_constraint(None, 'boards', type_='unique')
    op.drop_column('boards', 'shortLink')
    ### end Alembic commands ###
