"""add pagesList column

Revision ID: 3b551cd3d9e
Revises: 4e956f21c905
Create Date: 2015-04-13 10:29:03.003636

"""

# revision identifiers, used by Alembic.
revision = '3b551cd3d9e'
down_revision = '4e956f21c905'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.add_column('lists', sa.Column('pagesList', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_lists_pagesList'), 'lists', ['pagesList'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lists_pagesList'), table_name='lists')
    op.drop_column('lists', 'pagesList')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    ### end Alembic commands ###
