"""visibility to labels.

Revision ID: 486ddd937a70
Revises: 295ce675e7bf
Create Date: 2015-09-10 11:46:01.143036

"""

# revision identifiers, used by Alembic.
revision = '486ddd937a70'
down_revision = '295ce675e7bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('visible', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_labels_visible'), 'labels', ['visible'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labels_visible'), table_name='labels')
    op.drop_column('labels', 'visible')
    ### end Alembic commands ###
