"""cards have "closed" attribute

Revision ID: 4d56b1f86833
Revises: 1e3b6fd449
Create Date: 2015-07-23 16:14:09.904549

"""

# revision identifiers, used by Alembic.
revision = '4d56b1f86833'
down_revision = '1e3b6fd449'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('closed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'closed')
    ### end Alembic commands ###
