"""increase varchar sizes

Revision ID: 4e956f21c905
Revises: db9312279c8
Create Date: 2015-04-05 17:13:22.699226

"""

# revision identifiers, used by Alembic.
revision = '4e956f21c905'
down_revision = 'db9312279c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
ALTER TABLE users ALTER email TYPE text;
ALTER TABLE users ALTER COLUMN "fullName" TYPE text;
ALTER TABLE boards ALTER subdomain TYPE text;
ALTER TABLE boards ALTER name TYPE text;
    ''')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
