"""events table

Revision ID: 5a3b95894cc0
Revises: 41061c20744c
Create Date: 2015-10-03 13:37:50.772769

"""

# revision identifiers, used by Alembic.
revision = '5a3b95894cc0'
down_revision = '41061c20744c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('cents', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_kind'), 'events', ['kind'], unique=False)
    op.drop_column(u'boards', 'webhook')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'boards', sa.Column('webhook', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_events_kind'), table_name='events')
    op.drop_table('events')
    ### end Alembic commands ###
