"""keep a list of syndication destinations.

Revision ID: 962c2285f64
Revises: 280dbf4fee6e
Create Date: 2015-09-30 09:51:28.405691

"""

# revision identifiers, used by Alembic.
revision = '962c2285f64'
down_revision = '280dbf4fee6e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('syndicated', postgresql.ARRAY(sa.Text(), dimensions=1), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'syndicated')
    ### end Alembic commands ###
