"""comments

Revision ID: cc6053a120e
Revises: 4d56b1f86833
Create Date: 2015-07-26 12:50:26.146711

"""

# revision identifiers, used by Alembic.
revision = 'cc6053a120e'
down_revision = '4d56b1f86833'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_name', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('author_url', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('creator_id', sa.String(length=50), nullable=False))
    op.add_column('comments', sa.Column('raw', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('source_display', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('source_url', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'source_url')
    op.drop_column('comments', 'source_display')
    op.drop_column('comments', 'raw')
    op.drop_column('comments', 'creator_id')
    op.drop_column('comments', 'author_url')
    op.drop_column('comments', 'author_name')
    ### end Alembic commands ###
