"""support card covers

Revision ID: db9312279c8
Revises: 2c8e58c14c4c
Create Date: 2015-03-31 10:15:46.886083

"""

# revision identifiers, used by Alembic.
revision = 'db9312279c8'
down_revision = '2c8e58c14c4c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('cover', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'cover')
    ### end Alembic commands ###
