"""track users assigned to each card.

Revision ID: efa8e43ae42
Revises: 486ddd937a70
Create Date: 2015-09-10 12:39:49.454848

"""

# revision identifiers, used by Alembic.
revision = 'efa8e43ae42'
down_revision = '486ddd937a70'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('users', postgresql.ARRAY(sa.Text(), dimensions=1), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'users')
    ### end Alembic commands ###
